version: "3.5"

services:
  api01: &api
    image: henriqueccapozzi/rinha-2024q1-crebito
    hostname: api01
    # command: gunicorn --access-logfile - --error-logfile - -w 1 backend.wsgi -b 0.0.0.0:8000 --worker-connections 60
    # command: gunicorn -w 2 backend.wsgi -b 0.0.0.0:8000 --worker-connections 1000 -t4
    # command: gunicorn -w 2 backend.wsgi -b 0.0.0.0:8000 --worker-connections 30
    command: python3 wsgi_bjoern.py
    # command: gunicorn -w 2 -t 1 backend.wsgi -b 0.0.0.0:8000 --worker-connections 100 --access-logfile - --error-logfile -
    # command: python3 -m uvicorn backend.asgi:application --host 0.0.0.0 --port 8000
    # command: python3 -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 -w 2 --worker-connections 45
    environment:
      # - DB_HOSTNAME=db
      - DB_HOSTNAME=pgbouncer
      - PORT=8000
      - NUM_WORKERS=2
    ports:
      # - "9999:8000"
      - "8001:8000"
    volumes:
      - ./backend:/app
      # - ./secrets/.pg_pass:/app/.pg_pass
      # - ./secrets/.pg_service.conf:/app/.pg_service.conf
    depends_on:
      - db
      - pgbouncer
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8002:8000"
  # api03:
  #   <<: *api
  #   hostname: api03
  #   ports:
  #     - "8003:8000"
  # api04:
  #   <<: *api
  #   hostname: api04
  #   ports:
  #     - "8004:8000"


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

  pgbouncer:
    image: edoburu/pgbouncer:1.18.0
    hostname: pgbouncer
    # env_file:
    #   - ./.env
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
    environment:
      DATABASE_URL: "postgres://myuser:supersecret@db:5432/crebito"
      AUTH_TYPE: plain
      ADMIN_USERS: postgres,dbuser
      POOL_MODE: session
      # POOL_MODE: transaction
      MAX_DB_CONNECTIONS: "40"
      MAX_USER_CONNECTIONS: "40"
      DEFAULT_POOL_SIZE: "40"
      MIN_POOL_SIZE: "40"
      LOG_FILE: /dev/null
      LOG_CONNECTIONS: 0
      LOG_DISCONNECTIONS: 0
      LOG_POOLER_ERRORS: 0
      LOG_STATS: 0
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"


  db:
    image: postgres:latest
    hostname: db
    command: postgres -c 'shared_buffers=160MB' -c 'max_connections=50' -c checkpoint_timeout=600 -c max_wal_size=4096
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=myuser
      - POSTGRES_DB=crebito
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.90"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1